//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_infoGlobalNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Number { get; set; }
        public string Location { get; set; }
        public string Qualification { get; set; }
        public string Experience { get; set; }
        public string Resume { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public int JobId { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
